### ISSUE TITLE
File name get's cut-off after the first word

### ISSUE THREAD

**Issue by Junortiz** [mohad12211/TwitchDownloader-gui#2]
When downloading chat the default name for the file is chat.txt, I tried to change it to the stream title (which I think it should do by default) but the resulting file only contained the first word until the space (without the file format).

Example:
- Stream title: Surprise! Zero Time Dilemma starts NOW. Gotta keep you on your toes, weebs.
- File name: Surprise!

**Comment by Junortiz** [comment]
It seem that also happens when reading a file. If I change the name of the json file outside the program and try to render it, it will complain that the file doesn't exist because it takes the first word as the whole file name.

**Comment by mohad12211** [comment]
The project is still missing some small enhancements and bug fixes (like this, which an escaping bug), I was busy learning how to package for Debian and Fedora as it's my first time packaging software and it's such a frustrating process that I forgot I still need to finish the project first...
Thank you for reporting this! will do the final touches very soon.
